version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: turtlebot3-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: turtlebot3_db
      POSTGRES_USER: samma
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - turtlebot-network

  # Backend Spring Boot App
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: turtlebot3-backend
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://postgres:5432/turtlebot3_db
      - DB_USERNAME=samma
      - DB_PASSWORD=1234
      - ROSBRIDGE_URL=ws://rosbridge:9090
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rosbridge
    networks:
      - turtlebot-network

  # ROS Bridge WebSocket Server
  rosbridge:
    build:
      context: .
      dockerfile: rosbridge.Dockerfile
    image: local/rosbridge:humble
    container_name: turtlebot3-rosbridge
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - turtlebot-network

volumes:
  postgres_data:

networks:
  turtlebot-network:
    driver: bridge