# ros-stack/docker-compose.yml  (FINAL - dosyanın KENDİ klasörü baz alınır)
services:
  rosbridge:
    build:
      context: .
      dockerfile: rosbridge.Dockerfile
    container_name: rosbridge
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-42}
      - ROS_BRIDGE_PORT=${ROS_BRIDGE_PORT:-9090}
    ports:
      - "${ROS_BRIDGE_PORT:-9090}:9090"
    networks: [rosnet]

  tb3-sim:
    build:
      context: .
      dockerfile: tb3-sim.Dockerfile
    container_name: tb3-sim
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-42}
      - TURTLEBOT3_MODEL=${TURTLEBOT3_MODEL:-burger}
      - GAZEBO_WORLD=${GAZEBO_WORLD:-turtlebot3_world}
    depends_on: [rosbridge]
    volumes:
      - ./maps:/maps
    networks: [rosnet]

  tb3-slam:
    build:
      context: .
      dockerfile: tb3-slam.Dockerfile
    container_name: tb3-slam
    restart: unless-stopped
    depends_on: [rosbridge, tb3-sim]
    networks: [rosnet]

  tb3-nav:
    build:
      context: .
      dockerfile: tb3-nav.Dockerfile
    container_name: tb3-nav
    restart: unless-stopped
    environment:
      - MAP_FILE=${MAP_FILE:-/maps/map.yaml}
    depends_on: [rosbridge, tb3-sim, tb3-slam]
    volumes:
      - ./maps:/maps
    networks: [rosnet]

  rviz:
    build:
      context: .
      dockerfile: rviz.Dockerfile
    container_name: rviz-novnc
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-42}
      - DISPLAY=:0
      - GEOMETRY=1600x900x24
      - LIBGL_ALWAYS_SOFTWARE=1
    depends_on: [rosbridge]
    ports:
      - "6080:6080"         # noVNC (HTTP)
    networks: [rosnet]

networks:
  rosnet:
    driver: bridge
